baseURL = "https://yiqi0318.github.io/blog/"
title = "齐毅's Blog"
local = "en-gb"
theme = "yinyang"
defaultContentLanguage = "en"

[languages.en]
contentDir = "content/en"
label = "English"
weight = 1
[languages.cn]
contentDir = "content/cn"
label = "Chinese"
weight = 2

[[params.socials]]
name = "GitHub"
link = "https://github.com/yiqi0318/blog"
